version: '3'
services:
    api:
        build:
            context: api/.
        ports:
            - '8080:8080'

    robot:
        build:
            context: robot/.
        depends_on:
            - api
        links:
            - api:api
        volumes:
            - ./results:/home/app/results
